packages/mirai/README.md
packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box_parser.dart

This pull request includes updates to the `README.md` file and changes to the import statements in `mirai_colored_box_parser.dart`. The most significant changes are the addition of new badges and links in the `README.md` file and the modification of import paths in the parser file.
Updates to `README.md`:
* Added a GitHub Stars badge and a link to the stargazers page.
* Introduced a link to the Mirai Playground for users to experiment with the Mirai SDUI framework.
Changes to import statements:
* Changed import paths in `mirai_colored_box_parser.dart` to use specific paths within the `mirai` package and added a new import for `mirai_framework`.

chore: Update readme

---

website/docusaurus.config.ts

Update netlify configs

---

website/docs/widgets/text.md

Basic documentation for Mirai Text parser
Closes #77

docs: Add Mirai Test documentation

---

website/docs/widgets/wrap.md

1. Added docs for `MiraiWrap` widget.
Closes #80

feat: added docs for mirai wrap widget

---

.gitignore

Add `.netlify` folder to gitignore

chore: Add `.netlify` folder to gitignore

---

website/docs/widgets/listview.md

1. Added ListView Docs
Closes #55

feat: added listview docs

---

examples/mirai_gallery/ios/Podfile.lock
examples/mirai_gallery/pubspec.lock
packages/mirai/CHANGELOG.md
packages/mirai/README.md
packages/mirai/pubspec.yaml

This pull request includes updates to the `mirai` package, including a version bump, new features, and documentation improvements.
* [`packages/mirai/pubspec.yaml`](diffhunk://#diff-2c5a4d76ed61804dd4dbce2f74b2f105d25a678cdc8c99fdd16e03f6d31f3459L3-R3): Updated the package version from `0.7.2` to `0.8.0`.
* [`packages/mirai/CHANGELOG.md`](diffhunk://#diff-1e9985a1c54e2d2d3646a6fc6133c891bdc9faf025a0ef0dc46e3344f07e8f77R1-R11): Added changelog entries for version `0.8.0`, including new features such as Row and Column Spacing, Mirai carousel view, colored box parser, Divider widget support, and progress indicators. Also included a fix for replacing cache network image with `Image.network`.
* [`packages/mirai/README.md`](diffhunk://#diff-af22c2c59113b4d7af17e7f83476a0fd0de2c1872dc4e3e1350c08b …

chore: update to v0.8

---

website/docs/widgets/row.md

1. Added docs for Mirai Row widget.
Closes #62

docs: added mirai row docs

---

examples/mirai_gallery/assets/json/table_example.json
packages/mirai/lib/src/parsers/mirai_table/mirai_table.dart
packages/mirai/lib/src/parsers/mirai_table/mirai_table.freezed.dart
packages/mirai/lib/src/parsers/mirai_table/mirai_table.g.dart
packages/mirai/lib/src/parsers/mirai_table/mirai_table_parser.dart
website/docs/styles/border_radius.md
website/docs/styles/table_border.md

Simplify table border configuration
Closes #119

fix: Simplify table border configuration

---

website/docs/widgets/outlined_button.md

Add mirai outlined button documentation
Closes #57

docs: Add mirai outlined button documentation

---

website/docs/widgets/spacer.md

docs: Add Spacer widget documentation

---

website/docs/widgets/flexible.md

Add documentation for the flexible widget
Closes #46

docs: Add documentation for the flexible widget

---

website/docs/widgets/positioned.md
website/docs/widgets/stack.md

docs: Add stack and positioned widgets documentation

---

website/docs/widgets/app_bar.md

Add documentation for Mirai AppBar widget
Closes #28

Docs: Add documentation for Mirai AppBar widget

---

website/docs/widgets/fractionally_sized_box.md

Add documentation for Mirai FractionallySizedBox widget
Closes #49

Docs: Add documentation for Mirai FractionallySizedBox widget

---

packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog.dart
packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog.freezed.dart
packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog.g.dart
packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog_parser.dart
website/docs/widgets/alert_dialog.md

docs:  Update Alert Dialog and add docs

---

packages/mirai/lib/src/parsers/mirai_scaffold/mirai_scaffold.dart
packages/mirai/lib/src/parsers/mirai_scaffold/mirai_scaffold.freezed.dart
packages/mirai/lib/src/parsers/mirai_scaffold/mirai_scaffold.g.dart
packages/mirai/lib/src/parsers/mirai_scaffold/mirai_scaffold_parser.dart
website/docs/widgets/scaffold.md

feat: Update scaffold widget and add documentation

---

website/docs/widgets/aspect_ratio.md
website/docs/widgets/circular_progress_indicator.md
website/docs/widgets/colored_box.md
website/docs/widgets/elevated_button.md
website/docs/widgets/filled_button.md
website/docs/widgets/fitted_box.md
website/docs/widgets/floating_action_button.md
website/docs/widgets/icon_button.md
website/docs/widgets/linear_progress_indicator.md
website/docs/widgets/list_tile.md
website/docs/widgets/network_widget.md
website/docs/widgets/outlined_button.md
website/docs/widgets/radio_group.md
website/docs/widgets/safe_area.md
website/docs/widgets/sized_box.md
website/docs/widgets/table_cell.md
website/docs/widgets/table_row.md
website/docs/widgets/text_button.md
website/docs/widgets/text_field.md

docs: Add NetworkWidget documentation

---

packages/mirai/lib/src/parsers/mirai_elevated_button/mirai_elevated_button.dart
packages/mirai/lib/src/parsers/mirai_elevated_button/mirai_elevated_button.freezed.dart
packages/mirai/lib/src/parsers/mirai_elevated_button/mirai_elevated_button.g.dart
packages/mirai/lib/src/parsers/mirai_elevated_button/mirai_elevated_button_parser.dart
packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button.dart
packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button.freezed.dart
packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button.g.dart
packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart
packages/mirai/lib/src/parsers/mirai_outlined_button/mirai_outlined_button.dart
packages/mirai/lib/src/parsers/mirai_outlined_button/mirai_outlined_button.freezed.dart
packages/mirai/lib/src/parsers/mirai_outlined_button/mirai_outlined_button.g.dart
packages/mirai/lib/src/parsers/mirai_outlined_button/mirai_outlined_button_parser.dart
packages/mirai/lib/src/parsers/mirai_text_button/mirai_text_button.dart
packages/mirai/lib/src/parsers/mirai_text_button/mirai_text_button.freezed.dart
packages/mirai/lib/src/parsers/mirai_text_button/mirai_text_button.g.dart
packages/mirai/lib/src/parsers/mirai_text_button/mirai_text_button_parser.dart
website/docs/widgets/elevated_button.md
website/docs/widgets/filled_button.md
website/docs/widgets/outlined_button.md
website/docs/widgets/text_button.md

- Standardize FilledButton, OutlineButton, TextButton and ElevatedButton parameters.
Closes #150

feat: standardize parameters in buttons

---

packages/mirai/lib/src/parsers/mirai_card/mirai_card.dart
packages/mirai/lib/src/parsers/mirai_card/mirai_card.freezed.dart
packages/mirai/lib/src/parsers/mirai_card/mirai_card.g.dart
packages/mirai/lib/src/parsers/mirai_card/mirai_card_parser.dart
website/docs/widgets/card.md

Add Card widget documentation
Closes #32

docs: Add Card widget documentation

---

packages/mirai/lib/src/parsers/mirai_chip/mirai_chip.dart
packages/mirai/lib/src/parsers/mirai_chip/mirai_chip.freezed.dart
packages/mirai/lib/src/parsers/mirai_chip/mirai_chip.g.dart
packages/mirai/lib/src/parsers/mirai_chip/mirai_chip_parser.dart
website/docs/widgets/chip.md

feat: Update Chip widget with onDeleted, clipBehavior, visualDensity, materialTapTargetSize, avatarBoxConstraints & deleteIconBoxConstraints params

---

packages/stac/pubspec.yaml
packages/stac_framework/pubspec.yaml
packages/stac_webview/pubspec.yaml

Add pub.dev topics
- UI
- widgets
- Server-Driven-UI
- Dynamic-widgets
- UI
- widgets
- Server-Driven-UI
- Dynamic-widgets
- UI
- widgets
- Server-Driven-UI
- Dynamic-widgets
- webview-flutter
Closes #193

chore: Add pub.dev topics

---

examples/counter_example/pubspec.lock
examples/stac_gallery/pubspec.lock
packages/stac/lib/src/parsers/stac_elevated_button/stac_elevated_button.dart
packages/stac/lib/src/parsers/stac_elevated_button/stac_elevated_button.freezed.dart
packages/stac/lib/src/parsers/stac_elevated_button/stac_elevated_button.g.dart
packages/stac/lib/src/parsers/stac_elevated_button/stac_elevated_button_parser.dart
packages/stac/lib/src/parsers/stac_filled_button/stac_filled_button.dart
packages/stac/lib/src/parsers/stac_filled_button/stac_filled_button.freezed.dart
packages/stac/lib/src/parsers/stac_filled_button/stac_filled_button.g.dart
packages/stac/lib/src/parsers/stac_filled_button/stac_filled_button_parser.dart
packages/stac/lib/src/parsers/stac_outlined_button/stac_outlined_button.dart
packages/stac/lib/src/parsers/stac_outlined_button/stac_outlined_button.freezed.dart
packages/stac/lib/src/parsers/stac_outlined_button/stac_outlined_button.g.dart
packages/stac/lib/src/parsers/stac_outlined_button/stac_outlined_button_parser.dart
packages/stac/lib/src/parsers/stac_text_button/stac_text_button.dart
packages/stac/lib/src/parsers/stac_text_button/stac_text_button.freezed.dart
packages/stac/lib/src/parsers/stac_text_button/stac_text_button.g.dart
packages/stac/lib/src/parsers/stac_text_button/stac_text_button_parser.dart
website/docs/widgets/elevated_button.md
website/docs/widgets/filled_button.md
website/docs/widgets/outlined_button.md
website/docs/widgets/text_button.md

Remove IconAlignment from button widgets
Closes #

feat: Remove IconAlignment from button widgets

---

examples/stac_gallery/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.yaml

chore: upgrade melos

---

.vscode/launch.json
examples/stac_gallery/macos/Podfile.lock
examples/stac_gallery/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/stac_gallery/macos/Runner/AppDelegate.swift

Chore: Update configs 

---

packages/stac/lib/src/parsers/stac_color_scheme/stac_color_scheme.dart
packages/stac/lib/src/parsers/stac_color_scheme/stac_color_scheme.freezed.dart
packages/stac/lib/src/parsers/stac_color_scheme/stac_color_scheme.g.dart

fix: handle missing background field in ColorScheme to avoid null error
Closes #217

fixed null when background is missing from ColorScheme

---

website/docs/concepts/theming.md

Small PR - Commit 9e0cd39261fb7b41126a2ff5411db984ed344c12 moved `stac_theme.dart`. This PR adjusts sources to changes.
Closes #

docs: update `stac_theme.dart` reference

---

examples/counter_example/ios/Flutter/Debug.xcconfig
examples/counter_example/ios/Flutter/Release.xcconfig
examples/counter_example/ios/Podfile
examples/counter_example/macos/Flutter/Flutter-Debug.xcconfig
examples/counter_example/macos/Flutter/Flutter-Release.xcconfig
examples/counter_example/macos/Flutter/GeneratedPluginRegistrant.swift
examples/counter_example/macos/Podfile
examples/counter_example/pubspec.lock
examples/stac_gallery/ios/Podfile.lock
examples/stac_gallery/macos/Flutter/GeneratedPluginRegistrant.swift
examples/stac_gallery/pubspec.lock
packages/stac/lib/src/parsers/widgets/stac_image/stac_image_parser.dart
packages/stac/pubspec.yaml

feat: Replace networkImage with CachedNetwork Image

---

packages/stac/lib/src/framework/stac.dart
packages/stac/lib/src/parsers/widgets/stac_clip_rrect/stac_clip_rrect.dart
packages/stac/lib/src/parsers/widgets/stac_clip_rrect/stac_clip_rrect.freezed.dart
packages/stac/lib/src/parsers/widgets/stac_clip_rrect/stac_clip_rrect.g.dart
packages/stac/lib/src/parsers/widgets/stac_clip_rrect/stac_clip_rrect_parser.dart
packages/stac/lib/src/parsers/widgets/widgets.dart
packages/stac/lib/src/utils/widget_type.dart
website/docs/widgets/clip_rrect.md

feat: add ClipRRect widget support

---

examples/stac_gallery/assets/json/image_example.json
packages/stac/lib/src/framework/stac.dart
packages/stac/lib/src/parsers/widgets/stac_gesture_detector/stac_gesture_detector.dart
packages/stac/lib/src/parsers/widgets/stac_gesture_detector/stac_gesture_detector.freezed.dart
packages/stac/lib/src/parsers/widgets/stac_gesture_detector/stac_gesture_detector.g.dart
packages/stac/lib/src/parsers/widgets/stac_gesture_detector/stac_gesture_detector_parser.dart
packages/stac/lib/src/parsers/widgets/widgets.dart
packages/stac/lib/src/utils/widget_type.dart
website/docs/widgets/gesture_detector.md

Add GestureDetector widget support with tap, drag and press handlers

feat: Add GestureDetector widget support with tap, drag and press handlers

---

packages/stac/README.md

Chore: Update Maintainers in README.md
Closes #

Chore: Update Maintainers in README.md

---

packages/stac/lib/src/parsers/widgets/stac_gesture_detector/stac_gesture_detector_parser.dart

…ssary event handling
Add null checks for gesture detector callbacks to prevent unnecessary event handling

fix: add null checks for gesture detector callbacks to prevent unnecessary event handling
