examples/mirai_gallery/assets/json/carousel_view_example.json
examples/mirai_gallery/assets/json/home_screen.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view.dart
packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view.freezed.dart
packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view.g.dart
packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart

This pull request introduces a new feature for a carousel view in the Mirai framework. The changes include adding the necessary JSON configuration, updating the home screen to include the new carousel view, and implementing the carousel view parser and model.
Key changes include:
* [`packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view.dart`](diffhunk://#diff-62bcc553326c5cf5167598a63b2617a7cfc4d7b44663464befa7e4cf6ad8d479R1-R36): Added the `MiraiCarouselView` model with properties and JSON serialization.
* [`packages/mirai/lib/src/parsers/mirai_carousel_view/mirai_carousel_view_parser.dart`](diffhunk://#diff-9900889fe9c1b5ee6a3de7cd93b9d0722c10529845a4d95b8fa8be53012425e6R1-R57): Implemented the `MiraiCarouselViewParser` to parse the carousel view from JSON and render …

feat: Add Mirai carousel view with example

---

packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box.dart
packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box.freezed.dart
packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box.g.dart
packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart

This pull request introduces a new parser for `MiraiColoredBox` in the `mirai` package. The most important changes include adding the parser to the framework, defining the `MiraiColoredBox` class, and updating the necessary files to integrate this new parser.
New parser addition:
* [`packages/mirai/lib/src/framework/mirai.dart`](diffhunk://#diff-9a1f699d250950bd7ace1e9eb6495d3357e5d6e05dd59289b3c07f3bd754089cR84): Added `MiraiColoredBoxParser` to the list of parsers.
Definition and serialization:
* [`packages/mirai/lib/src/parsers/mirai_colored_box/mirai_colored_box.dart`](diffhunk://#diff-780d0d272fb216789443ee50be2242dd734c86fcd55d63e52c9a43bc632fcd6cR1-R17): Defined the `MiraiColoredBox` class with `freezed` and `json_serializable` support.
* …

feat: Add Mirai colored box parser

---

examples/mirai_gallery/macos/Flutter/GeneratedPluginRegistrant.swift
examples/mirai_gallery/pubspec.lock
packages/mirai/lib/src/parsers/mirai_image/mirai_image_parser.dart
packages/mirai/pubspec.yaml

Replace cached network image with Image.network as CachedNetworkImage is not supported on web.
Closes #10

fix: Replace cache network image with the Image.network.

---

examples/mirai_gallery/assets/json/divider_example.json
examples/mirai_gallery/assets/json/home_screen.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_divider/mirai_divider.dart
packages/mirai/lib/src/parsers/mirai_divider/mirai_divider.freezed.dart
packages/mirai/lib/src/parsers/mirai_divider/mirai_divider.g.dart
packages/mirai/lib/src/parsers/mirai_divider/mirai_divider_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart
pubspec.yaml

This PR introduces support for the **Divider widget**. It adds a new feature that allows the use of customizable dividers in the UI, including options for thickness, height, and color.This feature is useful for creating styled dividers in a server-driven UI, allowing dynamic customization based on JSON input.
Key changes:
- Added a `Divider` widget with customizable properties (thickness, height, color).
Closes #15

feat: Add support for the Divider widget

---

packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/framework/mirai_registry.dart

1. Added a feature where users will able to override the existing parsers and action_parsers.
2. This will provide better customization and flexibitlity.
Closes #17

feat: added ability to override mirai parsers and action_parsers.

---

examples/mirai_gallery/assets/json/circular_progress_indicator_example.json
examples/mirai_gallery/assets/json/home_screen.json
examples/mirai_gallery/assets/json/linear_progress_indicator_example.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_circular_progress_indicator/mirai_circular_progress_indicator.dart
packages/mirai/lib/src/parsers/mirai_circular_progress_indicator/mirai_circular_progress_indicator.freezed.dart
packages/mirai/lib/src/parsers/mirai_circular_progress_indicator/mirai_circular_progress_indicator.g.dart
packages/mirai/lib/src/parsers/mirai_circular_progress_indicator/mirai_circular_progress_indicator_parser.dart
packages/mirai/lib/src/parsers/mirai_linear_progress_indicator/mirai_linear_progress_indicator.dart
packages/mirai/lib/src/parsers/mirai_linear_progress_indicator/mirai_linear_progress_indicator.freezed.dart
packages/mirai/lib/src/parsers/mirai_linear_progress_indicator/mirai_linear_progress_indicator.g.dart
packages/mirai/lib/src/parsers/mirai_linear_progress_indicator/mirai_linear_progress_indicator_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart
website/docs/widgets/circular_progress_indicator.md
website/docs/widgets/linear_progress_indicator.md

Added CircularProgressIndicator support
Added LinearProgressIndicator support
Added Documentation for both indicators
https://github.com/user-attachments/assets/d2335a45-6718-4984-ad33-1da5a4a25510
Issue is not listed

feat: Added support for mirai progress indicators

---

website/docs/widgets/align.md

1. Added docs for Mirai Align Widget
Closes #27

feat: added docs for mirai align widget

---

examples/mirai_gallery/assets/json/home_screen.json
examples/mirai_gallery/assets/json/radio_example.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_mouse_cursor/mirai_mouse_cursor.dart
packages/mirai/lib/src/parsers/mirai_radio/mirai_radio.dart
packages/mirai/lib/src/parsers/mirai_radio/mirai_radio.freezed.dart
packages/mirai/lib/src/parsers/mirai_radio/mirai_radio.g.dart
packages/mirai/lib/src/parsers/mirai_radio/mirai_radio_parser.dart
packages/mirai/lib/src/parsers/mirai_radio_group/mirai_radio_group.dart
packages/mirai/lib/src/parsers/mirai_radio_group/mirai_radio_group.freezed.dart
packages/mirai/lib/src/parsers/mirai_radio_group/mirai_radio_group.g.dart
packages/mirai/lib/src/parsers/mirai_radio_group/mirai_radio_group_parser.dart
packages/mirai/lib/src/parsers/mirai_radio_group/mirai_radio_group_scope.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart
website/docs/widgets/radio_group.md

Added support for radio widget along with radio group
Issue not listed
https://github.com/user-attachments/assets/d21f8eba-9451-4631-8aa8-7b97fba25f05

feat: Added support for radio widget

---

website/docs/widgets/sized_box.md

Documentation for Mirai SizedBox
closes #66

docs: sizedbox documentation

---

website/docs/widgets/padding.md

1. Added docs for Mirai Padding widget.
Closes #58

docs: added mirai padding docs

---

examples/mirai_gallery/assets/json/home_screen.json
examples/mirai_gallery/assets/json/opacity_example.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_opacity/mirai_opacity.dart
packages/mirai/lib/src/parsers/mirai_opacity/mirai_opacity.freezed.dart
packages/mirai/lib/src/parsers/mirai_opacity/mirai_opacity.g.dart
packages/mirai/lib/src/parsers/mirai_opacity/mirai_opacity_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart
website/docs/widgets/opacity.md

Introduced Mirai Opacity widget and added an example to the Mirai gallery app

feat: Add support for Opacity widget

---

examples/mirai_gallery/assets/json/icon_example.json
packages/mirai/lib/src/parsers/mirai_icon/mirai_icon.dart
packages/mirai/lib/src/parsers/mirai_icon/mirai_icon.freezed.dart
packages/mirai/lib/src/parsers/mirai_icon/mirai_icon.g.dart

In this PR, I updated the default value of the `iconType` in the Mirai Icon widget to `material` and modified the icon example to include Cupertino icons.
Closes #98

Add material as default icon type and update icon example

---

website/docs/widgets/image.md

Add Mirai Image Parser Docs
The `Image` widget allows you to display an image in your Flutter app using JSON. It supports images from multiple sources, including assets, files, and network URLs, and provides customization options such as alignment, color, width, height, and fit.
Closes [#53](https://github.com/BuildMirai/mirai/issues/53)

docs: Add Mirai Image Parser Docs

---

website/docs/intro.md

This pull request includes updates to the `website/docs/intro.md` file to correct the GitHub repository links for the packages in the Miraiverse. The most important changes are:
Documentation updates:
* [`website/docs/intro.md`](diffhunk://#diff-2c4e27af73519cb13f2e5f0bb5d92e590ecae6e27f40e24b64e3700e0c0e3b03L16-R18): Updated the GitHub repository links for `mirai`, `mirai_framework`, and `mirai_webview` to point to the correct locations under the `BuildMirai` organization.

chore: Update package links in documentation

---

packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart

Changed the onPressed and onLongPress implementaion in MiraiFilledButton.dart to be similar to MiraiElevatedButton.dart
Closes #111

fix: filledButton onPressed and onLongPress Functionality

---

examples/mirai_gallery/assets/json/home_screen.json
examples/mirai_gallery/assets/json/placeholder_example.json
packages/mirai/lib/src/framework/mirai.dart
packages/mirai/lib/src/parsers/mirai_placeholder/mirai_placeholder.dart
packages/mirai/lib/src/parsers/mirai_placeholder/mirai_placeholder.freezed.dart
packages/mirai/lib/src/parsers/mirai_placeholder/mirai_placeholder.g.dart
packages/mirai/lib/src/parsers/mirai_placeholder/mirai_placeholder_parser.dart
packages/mirai/lib/src/parsers/parsers.dart
packages/mirai/lib/src/utils/widget_type.dart
website/docs/widgets/placeholder.md

The Mirai `Placeholder` widget allows you to build the Flutter Placeholder widget using JSON.
Closes #

Feat: Adding Support Placeholder

---

website/docs/widgets/switch.md

Created the documentation for switch widget
Closes #71

Doc: Create documentation for switch widget

---

website/docs/widgets/safe_area.md

docs: Added documentation for SafeArea
Closes #64

docs: Added documentation for SafeArea

---

website/docs/widgets/align.md
website/docs/widgets/aspect_ratio.md
website/docs/widgets/circular_progress_indicator.md
website/docs/widgets/container.md
website/docs/widgets/fitted_box.md
website/docs/widgets/image.md
website/docs/widgets/limited_box.md
website/docs/widgets/linear_progress_indicator.md
website/docs/widgets/list_tile.md
website/docs/widgets/listview.md
website/docs/widgets/opacity.md
website/docs/widgets/padding.md
website/docs/widgets/placeholder.md
website/docs/widgets/radio_group.md
website/docs/widgets/row.md
website/docs/widgets/safe_area.md
website/docs/widgets/sized_box.md
website/docs/widgets/slider.md
website/docs/widgets/switch.md
website/docs/widgets/table.md
website/docs/widgets/table_cell.md
website/docs/widgets/table_row.md
website/docs/widgets/text.md
website/docs/widgets/text_button.md
website/docs/widgets/text_field.md
website/docs/widgets/visibility.md
website/docs/widgets/wrap.md

docs: Add mirai text button documentation
Closes #78

docs: Add mirai text button documentation

---

website/docs/widgets/elevated_button.md

Add mirai elevated button documentation
Closes #43

docs: Add mirai elevated button documentation

---

website/docs/widgets/filled_button.md

Add mirai filled button documentation
Closes #44

docs: Add mirai filled button documentation

---

website/docs/widgets/floating_action_button.md

Add mirai floating action button documentation
Closes #47

docs: Add mirai floating action button documentation

---

website/docs/widgets/center.md

docs: Add documentation for the Center widget

---

website/docs/widgets/expanded.md

docs: Add documentation for the expanded widget

---

website/docs/widgets/column.md

Add documentation for the Mirai column widget
Closes #39

Docs: Add documentation for Mirai column widget

---

website/docs/widgets/circle_avatar.md

Add documentation for Mirai CircleAvatar widget
Closes #37

Docs: Add documentation for Mirai CircleAvatar widget

---

website/docs/widgets/form.md

Docs: Add documentation for Mirai Form widget

---

website/docs/widgets/single_child_scroll_view.md

Docs: Add documentation for SingleChildScrollView widget

---

packages/mirai/lib/src/parsers/mirai_default_tab_controller/mirai_default_tab_controller.dart
packages/mirai/lib/src/parsers/mirai_default_tab_controller/mirai_default_tab_controller.freezed.dart
packages/mirai/lib/src/parsers/mirai_default_tab_controller/mirai_default_tab_controller.g.dart
packages/mirai/lib/src/parsers/mirai_default_tab_controller/mirai_default_tab_controller_parser.dart
website/docs/widgets/default_tab_controller.md

docs: Add DefaultTabController documentation

---

website/docs/widgets/carousel_view.md

Add CarouselView documentation
Closes #33

docs: Add CarouselView documentation

---

website/docs/widgets/grid_view.md

Add GridView widget documentation
Closes #50

docs: Add GridView widget documentation

---

website/docs/widgets/page_view.md

Add PageView widget documentation
Closes #59

docs: Add PageView widget documentation

---

website/docs/widgets/text_form_field.md

Add TextFormField widget documentation
Closes #70

docs: Add TextFormField widget documentation

---

website/docs/widgets/bottom_navigation_bar.md

Add BottomNavigationBar widget documentation
Closes #30 #31

docs: Add BottomNavigationBar widget documentation

---

website/docs/actions/dialog..md
website/docs/actions/form_validate.md
website/docs/actions/get_form_value.md
website/docs/actions/modal_bottom_sheet.md
website/docs/actions/navigate.md
website/docs/actions/network_request.md
website/docs/actions/none.md

Add Mirai action parser docs
Closes #172 
Closes #173 
Closes #174 
Closes #175 
Closes #176 
Closes #177 
Closes #178

docs: Add Mirai action parser docs

---

CONTRIBUTING.md

chore: Add contribution guidelines

---

examples/stac_gallery/assets/json/dynamic_list_view_example.json
packages/stac/lib/src/parsers/widgets/stac_dynamic_view/stac_dynamic_view_parser.dart
website/docs/widgets/dynamic_view.md

Renamed all occurrences of `ItemTemplate` to `itemTemplate` for consistency with lower camelCase naming convention.
This includes:
- Parser logic
- JSON example files
- Documentation
Closes #230

fix: rename ItemTemplate → itemTemplate for consistency

---

examples/stac_gallery/assets/json/clip_oval_example.json
examples/stac_gallery/assets/json/home_screen.json
packages/stac/lib/src/framework/stac.dart
packages/stac/lib/src/parsers/widgets/stac_clip_oval/stac_clip_oval.dart
packages/stac/lib/src/parsers/widgets/stac_clip_oval/stac_clip_oval.freezed.dart
packages/stac/lib/src/parsers/widgets/stac_clip_oval/stac_clip_oval.g.dart
packages/stac/lib/src/parsers/widgets/stac_clip_oval/stac_clip_oval_parser.dart
packages/stac/lib/src/parsers/widgets/widgets.dart
packages/stac/lib/src/utils/widget_type.dart
website/docs/widgets/clip_oval.md

feat: add ClipOval widget support

---

examples/stac_gallery/assets/json/home_screen.json
examples/stac_gallery/assets/json/variable_example.json
examples/stac_gallery/assets/json/variable_navigate_example.json
examples/stac_gallery/lib/main.dart
packages/stac/lib/src/framework/stac.dart
packages/stac/lib/src/framework/stac_registry.dart
packages/stac/lib/src/parsers/actions/actions.dart
packages/stac/lib/src/parsers/actions/stac_navigate_action/stac_navigate_action_parser.dart
packages/stac/lib/src/parsers/actions/stac_set_value/stac_set_value_action.dart
packages/stac/lib/src/parsers/actions/stac_set_value/stac_set_value_action.freezed.dart
packages/stac/lib/src/parsers/actions/stac_set_value/stac_set_value_action.g.dart
packages/stac/lib/src/parsers/actions/stac_set_value/stac_set_value_action_parser.dart
packages/stac/lib/src/parsers/widgets/stac_set_value/stac_set_value.dart
packages/stac/lib/src/parsers/widgets/stac_set_value/stac_set_value.freezed.dart
packages/stac/lib/src/parsers/widgets/stac_set_value/stac_set_value.g.dart
packages/stac/lib/src/parsers/widgets/stac_set_value/stac_set_value_parser.dart
packages/stac/lib/src/parsers/widgets/widgets.dart
packages/stac/lib/src/utils/action_type.dart
packages/stac/lib/src/utils/variable_resolver.dart
packages/stac/lib/src/utils/widget_type.dart
packages/stac_framework/lib/src/stac_action_parser.dart
packages/stac_framework/lib/src/stac_parser.dart

Add variable support with the setValue widget and action
Closes #128

feat: add variable support with setValue widget and action

---

packages/stac/lib/src/parsers/widgets/stac_font_weight/stac_font_weight.dart
packages/stac/lib/src/parsers/widgets/stac_text/stac_text.dart
packages/stac/lib/src/parsers/widgets/stac_text_style/stac_text_style.g.dart

- Introduced `normal` and `bold` font weight options to the `StacFontWeight` enum.
- These additions allow for more common and intuitive font weight specifications, aligning with standard CSS and design practices.
- The generated code for `StacTextStyle` has also been updated to include these new enum values.
**Note**: 
```
/// The default font weight.
static const FontWeight normal = w400;
/// A commonly used font weight that is heavier than normal.
static const FontWeight bold = w700;
```
Closes #259

feat: add `normal` and `bold` to `StacFontWeight`

---

examples/stac_gallery/assets/json/container_example.json
examples/stac_gallery/lib/main.dart
packages/stac/lib/src/utils/color_utils.dart

Add support for color transparency using @ notation
```
{
"type": "container",
"color": "primary@50",
"height": 250,
"width": "maxFinite"
}
```
Closes #254

feat: add support for color transparency using @ notation

---

packages/stac/lib/src/parsers/stac_card_theme_data/stac_card_theme_data.dart
packages/stac/lib/src/parsers/stac_dialog_theme/stac_dialog_theme.dart
packages/stac/lib/src/parsers/stac_tab_bar_theme_data/stac_tab_bar_theme_data.dart

In order to be compatible with Flutter 3.32, this PR migrates `dialogTheme`, `tabBarTheme`, and `cardTheme` to `DialogThemeData`, `TabBarThemeData`, and `CardThemeData`, respectively. 
Closes #

refactor: migrate Theme classes to ThemeData classes 
